"""Offline provider that produces a deterministic templated NDA.

Used whenever ``--real`` is not passed, so the tool works with no API key and
no network access. The output is a genuine (if generic) NDA template.
"""

from __future__ import annotations

from ..models import NDARequest
from .base import Provider


class MockProvider(Provider):
    name = "mock"

    def generate(self, request: NDARequest) -> str:
        kind = "MUTUAL " if request.mutual else ""
        disclose = (
            "each party may disclose to the other"
            if request.mutual
            else f"{request.disclosing_party} (the \"Disclosing Party\") may disclose to "
            f"{request.receiving_party} (the \"Receiving Party\")"
        )
        date_str = request.effective_date.strftime("%B %d, %Y")

        return f"""{kind}NON-DISCLOSURE AGREEMENT

This {kind}Non-Disclosure Agreement (this "Agreement") is entered into as of
{date_str} (the "Effective Date") by and between {request.disclosing_party} and
{request.receiving_party} (each a "Party" and collectively the "Parties").

RECITALS

The Parties wish to explore {request.purpose} (the "Purpose"), and in connection
therewith {disclose} certain confidential and proprietary information. The Parties
enter into this Agreement to protect such information.

1. CONFIDENTIAL INFORMATION. "Confidential Information" means any non-public
   information disclosed by one Party to the other, whether orally, in writing, or
   by inspection of tangible objects, that is designated as confidential or that
   reasonably should be understood to be confidential given its nature and the
   circumstances of disclosure.

2. OBLIGATIONS. The Receiving Party shall (a) hold the Confidential Information in
   strict confidence, (b) use it solely for the Purpose, and (c) not disclose it to
   any third party without the prior written consent of the Disclosing Party.

3. EXCLUSIONS. Confidential Information does not include information that (a) is or
   becomes publicly available through no fault of the Receiving Party, (b) was
   rightfully known prior to disclosure, (c) is rightfully obtained from a third
   party without restriction, or (d) is independently developed without use of the
   Confidential Information.

4. TERM. This Agreement shall remain in effect for {request.term_years}
   year(s) from the Effective Date, and the confidentiality obligations herein shall
   survive for {request.term_years} year(s) following any termination.

5. RETURN OF MATERIALS. Upon written request, the Receiving Party shall promptly
   return or destroy all Confidential Information in its possession.

6. NO LICENSE. Nothing in this Agreement grants any rights in or to the
   Confidential Information except as expressly set forth herein.

7. GOVERNING LAW. This Agreement shall be governed by and construed in accordance
   with the laws of {request.jurisdiction}, without regard to its conflict of laws
   principles.

8. ENTIRE AGREEMENT. This Agreement constitutes the entire agreement between the
   Parties with respect to its subject matter and supersedes all prior agreements
   and understandings.

IN WITNESS WHEREOF, the Parties have executed this Agreement as of the Effective
Date.

{request.disclosing_party}                {request.receiving_party}

By: ____________________                  By: ____________________
Name:                                     Name:
Title:                                    Title:

[Generated by ndaconstruct (mock provider) — not legal advice.]
"""
